package Exception_Handeling;
import java.util.InputMismatchException;
import java.util.Scanner;

public class TryCatch {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter Numerator");
		int num = sc.nextInt();
		
		System.out.println("Enter Denomerator");
		int den = sc.nextInt();
		
		try
		{
			int ans = num/den;
		}
		catch (ArithmeticException e) 
		{
			try 
			{
				System.out.println(10/0);
			}
			catch (Exception e1) 
			{
				System.out.println(e1);
			}
				System.out.println("Cann't be divide by 0 "+e);
		}
		catch (InputMismatchException e) {
			try{
				sc = new Scanner(System.in);
				System.out.println("Enter no.");
				int n1 = sc.nextInt();
				System.out.println("Enter no2.");
				int n2 = sc.nextInt();
				System.out.println(n1 + n2);
			}
			catch (Exception e1) {
				System.out.println("Ther is an exception "+e1);
			}
		}
		System.out.println("hello");
		int dnum = sc.nextInt();
		System.out.println(dnum);
		System.out.println("heheh");
	}

}
